### ISSUE TITLE
Error: 500 Internal Server Error

### ISSUE THREAD

**Issue by djkarts** [geddy/geddy#434]
$ npm -v
1.3.5
$ node -v
v0.10.15
$ geddy -v
0.9.13

I am following the Geddy tutorial for todo app. I get the following error when I create a todo resource in todo_app at http://localhost:4000/todos/

As recommended I typed:
$ cd todo_app
$ geddy
$ geddy gen scaffold todo title:default status

Received the following error:

Error: 500 Internal Server Error

Error: Partial template "app/views/todos/index" not found in app/views, app/views/todos and app/views/layouts
at Partial.getTemplateData (/usr/local/lib/node_modules/geddy/lib/template/partial.js:85:15)
at Partial.render (/usr/local/lib/node_modules/geddy/lib/template/partial.js:95:29)
at /usr/local/lib/node_modules/geddy/lib/template/partial.js:136:15
at Array.forEach (native)
at Partial.renderChildren (/usr/local/lib/node_modules/geddy/lib/template/partial.js:135:16)
at handleData (/usr/local/lib/node_modules/geddy/lib/template/partial.js:100:16)
at /usr/local/lib/node_modules/geddy/lib/template/partial.js:117:9
at fs.js:266:14
at Object.oncomplete (fs.js:107:15)

I am running OSX 10.6.8 but i received the same error on my Ubuntu machine I ran as an AWS instance. Please help!!

**Comment by musman92** [comment]
there is one '{' bracket missing so it gives to unexpected token error
its bug in tutorial
