### ISSUE TITLE
Broken _session_store.json

### ISSUE THREAD

**Issue by phanect** [geddy/geddy#666]
Sometimes content of _session_store.json is invalid and I get following error.

```
TypeError: Cannot read property 'accessTime' of undefined
    at get (/home/phanect/.nvm/v0.10.35/lib/node_modules/geddy/lib/sessions/index.js:130:21)
    at isExpired (/home/phanect/.nvm/v0.10.35/lib/node_modules/geddy/lib/sessions/index.js:108:36)
    at localCallback (/home/phanect/.nvm/v0.10.35/lib/node_modules/geddy/lib/sessions/index.js:95:16)
    at /home/phanect/.nvm/v0.10.35/lib/node_modules/geddy/lib/sessions/stores/filesystem.js:58:7
    at /home/phanect/.nvm/v0.10.35/lib/node_modules/geddy/lib/sessions/stores/filesystem.js:90:7
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)
```
I opened _session_store.json and the content is:

```
"\"\"nnXhpgZgV0cO4bCie5O52ZpK7sy2vsfWVMGxPqedStbj2aQbrU0m8IwjoRkzBj3gsRiqrHX8wTruo3bhKqtjiKVaUdBbyLDDburWoa0qJHF1Jl4wsrpl3VI0rTsZw5Zt\":{\"accessTime\":1422252505152,\"flashMessages\":{}}}"
```

This is significantly invalid JSON.

On another occasion, the content of _session_store.json is:

```
{"HgNViZTklG6kHm31kKBjYNcY8wAmY0ptDTT0SLtzy2yocPq0FPv6a6guLu1z6kxCn60dK5oIPw6kzCXFwGdeVpUF59hnfkwVjPgFcMcOCGOhxcQFg4u74Z73t1YsAFPS":{"accessTime":1422246156196,"flashMessages":{}},"cs8HbBmqTLHQYuBY82Y7TAZdbcOtZNaacxBxxnxmIHZAzfLJHuUslkl4HvOJxUube3DLcrCnEQT7qheWkjnMpuKNd63cSUbmeU7BkCEyz6iyxpga6rcL0aSzkrqNEzeV":{"accessTime":
1422247307231,"flashMessages":{}},"KQliOMfSr26SYfjflFVFSsSN3lApte4iN3PsFVJhQcvf8W3UE3xzMdIgpl0oKmZcaq6CO1gi2pWwu9gdQGVw1M608XqPnhrsZykh8mCqDwh0DrLaRuRrUNFtcCyc7ga1":{"accessTime":1422247307239,"flashMessages":{}},"B862PobriZ2dYAnHYyDx34aXWnzjvbDYXpnKIEOnIgwKGjhQ0JlZuQxbfPA1qhacH0dMvPVKqTIf0IX7eu2cXmZ2ilKnxskAxWJhl4SUE392dKJKqeO9hRz70nsOtEcv":{"accessTime":1422247656019,"flashMessages":{}},"
xbNTj3ksoXHU4RtoGfXNaVMmaQUZ9nGYs4XyZEZjWK5FSbJtOwxFxUymQshxZ44Uvx1Jbvvsrj0fL9OcsTET2dU8oflP2TPcoVQImQ38RuOVdi47qsmjOpdFPcQd5Boc":{"accessTime":1422247656027,"flashMessages":{}}, /* ... */ }
```

It may be difficult to find out where the problem is from above, but see the last character of second line and first character of third line.

The property name includes line break:
```
"
xbNTj3ksoXHU4RtoGfXNaVMmaQUZ9nGYs4XyZEZjWK5FSbJtOwxFxUymQshxZ44Uvx1Jbvvsrj0fL9OcsTET2dU8oflP2TPcoVQImQ38RuOVdi47qsmjOpdFPcQd5Boc":{"accessTime":1422247656027,"flashMessages":{}}, // ...
```

**Comment by phanect** [comment]
I updated to current `master`, and now above error is not shown.
However, following error is shown instead:

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Filesystem._getDatastore (/home/phanect/.nvm/v0.10.35/lib/node_modules/geddy/lib/sessions/stores/filesystem.js:69:19)
    at Filesystem.write (/home/phanect/.nvm/v0.10.35/lib/node_modules/geddy/lib/sessions/stores/filesystem.js:58:26)
    at close (/home/phanect/.nvm/v0.10.35/lib/node_modules/geddy/lib/sessions/index.js:146:19)
    at utils.mixin.beginOutput (/home/phanect/.nvm/v0.10.35/lib/node_modules/geddy/lib/controller/base_controller.js:505:20)
    at utils.mixin.output (/home/phanect/.nvm/v0.10.35/lib/node_modules/geddy/lib/controller/base_controller.js:533:10)
    at cb (/home/phanect/.nvm/v0.10.35/lib/node_modules/geddy/lib/controller/base_controller.js:655:16)
    at utils.mixin.respond (/home/phanect/.nvm/v0.10.35/lib/node_modules/geddy/lib/controller/base_controller.js:684:7)
    at self.Model.create.then.catch.self.respond.format (/home/phanect/dev/notel-api/app/controllers/application.js:36:9)
    at tryCatch1 (/home/phanect/dev/notel-api/node_modules/sequelize/node_modules/bluebird/js/main/util.js:45:21)
```

**Comment by phanect** [comment]
Close for now. Sorry, I couldn't find the actual cause.

**Comment by koluchi** [comment]
I have same error. I used filesystem session store and problem i think is in this code
geddy/lib/sessions/stores/filesystem.js:87
```javascript
this._getDatastore = function (callback) {
      fs.readFile(this.filename, function (err, d) {
        var data;

        if (err) {
          return callback(null, {});
        }
        data = d.toString();
        try {
          data = JSON.parse(data);
          callback(null, data);
        }
        catch (e) {
          console.error('Could not parse session store, using empty session');
          callback(null, {});
        }
      });
    };
```
data = d.toString();
data is in global scope, that is very bad idia or just small bug )))

**Comment by deveshsinghal22** [comment]
Hi @phanect 

Any idea on this. I am getting this error when refresh page multiple times at once.

**Comment by phanect** [comment]
@deveshsinghal22 I haven't investigated the cause.

Current workarounds are:
1. Delete _session_store.json when it is broken (Sometimes it doesn't work)
2. Use memory as session store (I've never tried)

**Comment by deveshsinghal22** [comment]
Hi @phanect 
deleting _session_store.json is not a good idea when app is in production. It will logout all the users.
and I have tried the memory session but it did not worked well on heroku server. The only best option is mongo session but it is also disabled due to mongolab mongo3 upgrades.

**Comment by koluchi** [comment]
this._getDatastore method were contain a bug (geddy/lib/sessions/stores/filesystem.js::87). Using variable "data" was global.

**Comment by deveshsinghal22** [comment]
Hi @koluchi  
I am using geddy version 13.0.3. In which version this was fixed?

**Comment by phanect** [comment]
> deleting _session_store.json is not a good idea when app is in production.

I suggested that as workaround on development environment.

In my experience, I have never seen web apps using file system as session
store on production. They use DB so that multiple app servers can share
session info under load balanced environment.
You might also need additional file permission settings to allow node to
create _session_store.json.


I didn't noticed that this issue is fixed in current master, but according
to @koluch this is fixed in latest development version.
You can install latest master by

npm install [-g] geddy/geddy [--save]
-- 

Jumpei Ogawa (小川 純平)
Software Engineer, GrowAsPeople <http://growaspeople.org>

**Comment by phanect** [comment]
ps.
I'm not sure if we can release next version.
Founder @mde is not active on this project for more than 6 monthes. I and
@der-On are relatively active than others but don't contribute so much.

My company project which I use geddy is abandoned, and in next project I
should use more modern framework such as loopback, aurelia, and meteor,
rather than traditional MVC framework. So my contribution should be less.

If you prefer traditional MVC FW, I recommend another one such as Express.

-- 

Jumpei Ogawa (小川 純平)
Software Engineer, GrowAsPeople <http://growaspeople.org>

**Comment by koluchi** [comment]
@deveshsinghal22 
geddy@13.0.8 
latest from npm

**Comment by phanect** [comment]
I believe it is not fixed in 13.0.8.
At least this issue still happens in my environment.

**Comment by deveshsinghal22** [comment]
@koluchi Thanks

@phanect ok, Thanks for the update. I will try to update geddy with a different wrapper as mongo is the best option for session management.

**Comment by koluchi** [comment]
ps but i just exec npm install in project folder
