### ISSUE TITLE
Ambiguous error stack traces

### ISSUE THREAD

**Issue by AlexRaylight** [geddy/geddy#713]
Some errors contain the exact same useless stack trace:

```
Error
    at createConstructor (C:\Users\Gabi\AppData\Roaming\npm\node_modules\geddy\lib\response\errors.js:68:34)
    at new <anonymous> (C:\Users\Gabi\AppData\Roaming\npm\node_modules\geddy\lib\response\errors.js:79:33)
    at Object.<anonymous> (C:\Users\Gabi\AppData\Roaming\npm\node_modules\geddy\lib\response\errors.js:21:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Gabi\AppData\Roaming\npm\node_modules\geddy\lib\controller\responder\index.js:6:14)
```

I have noticed the same exact message being displayed for the following cases:
- Accessing/using a view that doesn't exist
- Accessing a table that doesn't exist (migration not run yet)
- Going to the /users routes after generating auth (#702)

**Comment by mde** [comment]
Sounds like we might need a release -- can you verify?
