### ISSUE TITLE
please help me!!! how to do?

### ISSUE THREAD

**Issue by 609926202** [geddy/geddy#722]
Error at createConstructor (/usr/lib/node_modules/geddy/lib/response/errors.js:68:34) at new <anonymous> (/usr/lib/node_modules/geddy/lib/response/errors.js:79:33) at Object.<anonymous> (/usr/lib/node_modules/geddy/lib/response/errors.js:21:10) at Module._compile (module.js:413:34) at Object.Module._extensions..js (module.js:422:10) at Module.load (module.js:357:32) at Function.Module._load (module.js:314:12) at Module.require (module.js:367:17) at require (internal/module.js:20:19) at Object.<anonymous> (/usr/lib/node_modules/geddy/lib/controller/responder/index.js:6:14)

**Comment by 609926202** [comment]
add

**Comment by 609926202** [comment]
add  npm install -g geddy/geddy

**Comment by 609926202** [comment]
have a problem
Error: 500 Internal Server Error
Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'OFFSET 4 LIMIT 4' at line 3 at Query.Sequence._packetToError (/home/wwwroot/Date_web_wechat/program/node_modules/mysql/lib/protocol/sequences/Sequence.js:30:14) at Query.ErrorPacket (/home/wwwroot/Date_web_wechat/program/node_modules/mysql/lib/protocol/sequences/Query.js:82:18) at Protocol._parsePacket (/home/wwwroot/Date_web_wechat/program/node_modules/mysql/lib/protocol/Protocol.js:197:24) at Parser.write (/home/wwwroot/Date_web_wechat/program/node_modules/mysql/lib/protocol/Parser.js:62:12) at Protocol.write (/home/wwwroot/Date_web_wechat/program/node_modules/mysql/lib/protocol/Protocol.js:37:16) at Socket.ondata (_stream_readable.js:536:20) at emitOne (events.js:95:20) at Socket.emit (events.js:182:7) at readableAddChunk (_stream_readable.js:153:18) at Socket.Readable.push (_stream_readable.js:111:10) -------------------- at Protocol._enqueue (/home/wwwroot/Date_web_wechat/program/node_modules/mysql/lib/protocol/Protocol.js:110:26) at Connection.query (/home/wwwroot/Date_web_wechat/program/node_modules/mysql/lib/Connection.js:148:25) at utils.mixin.exec (/usr/lib/node_modules/geddy/node_modules/model/lib/adapters/sql/mysql.js:121:24) at Timeout._onTimeout (/usr/lib/node_modules/geddy/node_modules/model/lib/adapters/sql/base.js:493:40) at tryOnTimeout (timers.js:224:11) at Timer.listOnTimeout (timers.js:198:5)

**Comment by 609926202** [comment]
I FIND THIS IS ERROR
{skip:4,limit:4}、{skip:10,limit:20}、{skip:3,limit:6}
how do?

**Comment by gabe-alex** [comment]
@mde This problem seems fixed in the latest "model" code, however the version on npm is an older one.

**Comment by 609926202** [comment]
@gabe-alex how to update?

**Comment by arvindstutzen** [comment]
@609926202 
npm install -g geddy/geddy

**Comment by ckhatton** [comment]
@609926202 Is this issue resolved now?
