### ISSUE TITLE
Node 8.1.2 public ressources error

### ISSUE THREAD

**Issue by TimDorand** [geddy/geddy#740]
Geddy doesn't load the public ressources stored in `/public/*`
Log: 
```
[Fri, 21 Jul 2017 09:44:44 GMT] ERROR ::1 - - [Fri Jul 21 2017 11:44:43 GMT+0200 (CEST)] "GET /favicon.ico 1.1" 500 1348 "http://localhost:4000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36 OPR/46.0.2597.32"
TypeError: Second argument needs to be a buffer
    at Object.fs.read (fs.js:669:11)
    at streamChunk (/home/tdorand/.nvm/versions/node/v8.1.2/lib/node_modules/geddy/lib/response/index.js:139:16)
    at /home/tdorand/.nvm/versions/node/v8.1.2/lib/node_modules/geddy/lib/response/index.js:154:11
    at FSReqWrap.oncomplete (fs.js:135:15)

```

I had to switch back to node 7.9.0
```
->       v7.9.0
         v8.1.2
```

**Comment by phanect** [comment]
Unfortunately Geddy is not actively developed now, and it only work on Node 6.x.

**Comment by mde** [comment]
Let's keep this open -- should be a relatively easy fix.

**Comment by ramyfarid922** [comment]
I faced this too while starting the app. It loaded the main index page but without the bootstrap files and the error is not revealing anything. It's just faulty out of the box!

**Comment by mde** [comment]
Fixed in master, b8c3a2e73bd4fb809bbfe1d00d154163d82578dd. I'll push out a new release if someone else can verify fixed.

**Comment by ckhatton** [comment]
@TimDorand @ramyfarid922 

Possible for either of you to verify that it is fixed? :octocat:

**Comment by Casblanca** [comment]
Thanks, already helped me.

**Comment by abrakadobr** [comment]
i'm sorry, lazy to do nice patch...

file geddy/lib/response/index.js
lines 140 +-

```
//my new code for file reading
        fs.readFile(filepath,(err,fileData)=>{
          console.log(['FILE',fileData.length,fileData])
          self.resp._length = fileData.length;
          self.resp.write(fileData, encoding);
          self.resp.end();
        })
/*
and commended after this line
// From Paperboy, http://github.com/felixge/node-paperboy
*/
```
